### ISSUE TITLE
ConcurrentModificationException when calling "generate code"

### ISSUE THREAD

**Issue by simare** [cedricziel/idea-php-typo3-plugin#104]
In v0.2.26 I get this exception when opening the generate code dialog.
I use PhpStorm 2017.3 on macOS High Sierra
[exception.txt](https://github.com/cedricziel/idea-php-typo3-plugin/files/1518534/exception.txt)

**Comment by cedricziel** [comment]
Thx for the report. It occurs when *opening* the dialogue?

**Comment by simare** [comment]
Hi, 
exactly. I open the `Generate` dialog and phpstorm shows an pop up window with an error message.

**Comment by cedricziel** [comment]
Can you reindex and try again when finished?

**Comment by simare** [comment]
Ok, that did the trick - also `Action` appeared in the menu.
Thank you!

**Comment by cedricziel** [comment]
I need to trigger the indexing after an update.

The action should also be unavailable, when the project is not indexed yet
