### ISSUE TITLE
 'allowed' => '*' in TCA adds "Missing table definition"

### ISSUE THREAD

**Issue by sgrossberndt** [cedricziel/idea-php-typo3-plugin#132]
Using `'allowed' => '*',` in a TCA definition leads to a warning `"Missing table definition"`.

```
        'items' => [
            'label' => 'LLL:EXT:lang/Resources/Private/Language/locallang_tca.xlf:sys_category.items',
            'config' => [
                'type' => 'group',
                'internal_type' => 'db',
                'allowed' => '*',
                'MM' => 'sys_category_record_mm',
                'MM_oppositeUsage' => [],
                'size' => 10,
                'fieldWizard' => [
                    'recordsOverview' => [
                        'disabled' => true,
                    ],
                ],
            ],
        ],
```

TYPO3 core does not explicitly state this option exists in the documentation but uses it itself and also checks for it in `RelationHandler` and `DatabaseIntegrityCheck`.

The plugin should not warn about `'allowed' => '*',`

**Comment by cedricziel** [comment]
Good catch, thx @sgrossberndt !

**Comment by sgrossberndt** [comment]
`'allowed' => 'index_config,pages',` leads to a warning too - the current implementation only checks for a single table?

**Comment by cedricziel** [comment]
Yes, indeed

**Comment by sgrossberndt** [comment]
By the way I installed this plugin this morning and I am already in love! Thanks a lot!

**Comment by cedricziel** [comment]
Great - keep the feature requests and bug reports coming then!

**Comment by sgrossberndt** [comment]
```
		'file' => [
			'config' => [
				'type' => 'group',
				'internal_type' => 'file',
				'allowed' => 'pdf',
				'uploadfolder' => 'uploads/tx_foo',
				'size' => 1
			]
		],
```

when `'internal_type'` is `'file'`, `'allowed'` does not contain a table definition

**Comment by cedricziel** [comment]
FYI: I'll split this up
