### ISSUE TITLE
Show warning instead of error when using xml instead of xlf path

### ISSUE THREAD

**Issue by sgrossberndt** [cedricziel/idea-php-typo3-plugin#135]
An old definition for a core file (using `.xml` instead of `.xlf`) e.g. 
`['LLL:EXT:lang/locallang_common.xml:yes', '1'],`
currently generates an error for a missing file. This is wrong as the core adapts the path and displays the content from the xlf file anyway. Its good to know and change this, but it should be a warning instead of an error.

**Comment by cedricziel** [comment]
Btw: are you using v0.2.39?

**Comment by sgrossberndt** [comment]
v0.2.36 as this is what I get offered when browsing plugins in PHPStorm

**Comment by cedricziel** [comment]
v0.2.39 is the current version - unfortunately the approval for new releases takes JetBrains round about 5 to 6 day

**Comment by sgrossberndt** [comment]
Still happens on v0.2.39.`

**Comment by cedricziel** [comment]
Alright, so let me get this straight, so I can implement i correctly:

The core sort of overlays the xml strings with xlf ones? Do you happen to know where the code for that behaviour is, so I can grasp it more thoroughly?

**Comment by cedricziel** [comment]
By the way: I think this is still worth highlighting - but more like highlighting with quickfix.

**Comment by sgrossberndt** [comment]
Using core lang files with `.xml` is deprecated but in order to keep backwards compatibility core lang files referenced with `xml` are redirected to `xlf`.

I am totally with you (as I wrote in the first message here: `Its good to know and change this, but it should be a warning instead of an error.`

**Comment by cedricziel** [comment]
Okay, thank you - that's definitely new to me. Can you point me to the place where the core performs the fallback?

**Comment by sgrossberndt** [comment]
Just tested it. This mechanism still works in TYPO3 7.6 but is gone in TYPO3 8.7. Wasting time on that is not worth it - let it be shown as an error and fixed by the dev to `xlf` - those are there in TYPO3 7.6 as well and should be used.

**Comment by cedricziel** [comment]
Alright - thx for your efforts to get this straight :)
