### ISSUE TITLE
Unresolved translation in modules

### ISSUE THREAD

**Issue by Smove** [cedricziel/idea-php-typo3-plugin#145]
When I'm using 
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModule` or `\TYPO3\CMS\Extbase\Utility\ExtensionUtility::registerModule`, the plugin throws "Unresolved translation" on 'labels' setting. 

The xlf files behind 'labels' has fixed entries, so only the filepath must be set.

![image](https://user-images.githubusercontent.com/3686891/34764265-3c0b90dc-f5ee-11e7-83ad-6cf2039bb70d.png)

![image](https://user-images.githubusercontent.com/3686891/34764277-48ab9850-f5ee-11e7-9ccd-b80b3a001f91.png)

**Comment by cedricziel** [comment]
I see. Yeah, this seems to be a general topic or rather an inconsistency i see in the "TYPO3 way".

How should I deal with this, implementation-wise? Should I create a bunch of exceptions for specific methods (bad)? Or should I assume that a `LLL:` prepended string is also okay-ish if it doesnt query a specific index (which could also lead to confusion)?

If I had a wish regarding this, I'd ask for changing the usage of the strings here. IMHO an `EXT:` prepended string should be enough.

**Comment by Smove** [comment]
Is there any way to add some code parts to an "ignore list"? Maybe the user should choose if this should be ignored.

**Comment by cedricziel** [comment]
AFAIK you can always ignore inspections through the code intentions menu (ALT+Enter on Linux) and there suppress warning or something.

**Comment by Smove** [comment]
Not working for me.

![image](https://user-images.githubusercontent.com/3686891/34767951-c2451a32-f5f9-11e7-92da-2107c7127846.png)


Maybe there really should be a change on the core side, but until then i would prefer the "bunch of exceptions" way.

**Comment by velletti** [comment]
The same problem exists in any Extension \Configuration\TCA\ExampleModel.php

return array(
	'ctrl' => array(
		'title'	=> 'LLL:EXT:jv_events/Resources/Private/Language/locallang_db.xlf:tx_jvevents_domain_model_event',
....
If the LLL resource starts with FILE:LLL:exgt  there is no code inspection error in PHP Storm, but tahts not the TYPO3 wants the label :-)

**Comment by cedricziel** [comment]
@velletti 

```
LLL:EXT:jv_events/Resources/Private/Language/locallang_db.xlf:tx_jvevents_domain_model_event
```
That's a valid label and it should be inspected.

* did you register `*.xlf` as xml file type?
* does a reindex fix the problem?
* if it doesnt, your `jv_events` extension is probably not detected correctly, because it doesnt follow the convention for extensions (https://github.com/cedricziel/idea-php-typo3-plugin/issues/87#issuecomment-346617136)

**Comment by velletti** [comment]
I feel sorry: , it was my fault : *.xlf  was registered as Type Text File in PHP Storm since i installed the last Update.  

Changing file type of xlf to XML solved my problem.  THANKS a lot for this great plugin !

**Comment by cedricziel** [comment]
@velletti I'm glad it helps ;)

**Comment by sgrossberndt** [comment]
I still have this issue in ```
	\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addModule(
		'xxx', '', '', '',
		[
			'routeTarget' => 'xxx',
			'access' => 'user,group',
			'name' => 'xxx',
			'icon' => 'EXT:xxx/ext_icon.svg',
			'labels' => 'LLL:EXT:xxx/Resources/Private/Language/locallang_mod.xml'
		]
	);
```
where `EXT:xxx/Resources/Private/Language/locallang_mod.xml` is a existing file used by TYPO3.

This also happens with TYPO3 core xlf files: `TYPO3_8-7/typo3/sysext/core/ext_tables.php` has several "Unresolved translation" errors:

```
        'web' => [
            'labels' => 'LLL:EXT:lang/Resources/Private/Language/locallang_mod_web.xlf',
            'name' => 'web',
            'iconIdentifier' => 'module-web'
        ],
```

**Comment by fjacobi** [comment]
Is it possible that this inspection can't be disabled or is using the wrong check?
![2018-02-02 10_52_00-settings](https://user-images.githubusercontent.com/861791/35727075-3885f9b8-0807-11e8-8920-718b488f0076.jpg)
![2018-02-02 10_52_13-news_ e__repos_news _-_ _configuration_tca_tx_news_domain_model_news php_ news](https://user-images.githubusercontent.com/861791/35727073-386ad82c-0807-11e8-9029-9b88e6eb41a1.jpg)

Even a direct suppression won't work, as stated in https://github.com/cedricziel/idea-php-typo3-plugin/issues/145#issuecomment-358603914

**Comment by rowild** [comment]
+1 Would like to upvote on this feature! Most appreciated!

**Comment by dahaupt** [comment]
@cedricziel Thanks for updating this plugin! Unfortunately, I'm still getting the error message with the latest version. I also tried invalidating my cache.

**Comment by cedricziel** [comment]
Can you share an example?

**Comment by dahaupt** [comment]
@cedricziel We are using it like this in `ext_tables.php`:

![image](https://user-images.githubusercontent.com/15915048/38216570-7c294ace-36cb-11e8-9f83-c698f6dc00fc.png)

**Comment by cedricziel** [comment]
@dahaupt i think this stems from your project setup. Please check the list in #87 (https://github.com/cedricziel/idea-php-typo3-plugin/issues/87#issuecomment-346617136)

**Comment by dahaupt** [comment]
@cedricziel Got it! My extensions `composer.json` was missing the part:

```
"extra": {
        "typo3/cms": {
            "extension-key": "isk_courses"
        }
    }
```

I generated the extension with the extension builder, probably it's not following the convention correcly. Thanks anyway for your hint. 😄 🍻

**Comment by cedricziel** [comment]
Alrighty! Thx for the heads-up! 😀

**Comment by rowild** [comment]
Hi! Thanks for the update! It works!!!

**Comment by dahaupt** [comment]
I get the same issue for `ÈXT:lang/` references. References to my extension language files work fine.

**Comment by Smove** [comment]
You should update our references. Take a look at https://docs.typo3.org/typo3cms/extensions/core/Changelog/8.5/Deprecation-78647-MoveLanguageFilesFromEXTlanglocallang_ToResourcesPrivateLanguage.html

**Comment by rowild** [comment]
They are updated. And it happens with my own language files, too, as the image shows...

![screen shot 2018-04-04 at 13 13 46](https://user-images.githubusercontent.com/213803/38304536-2284e6e6-380a-11e8-9743-dd3e03ec2da3.png)

Any ideas?
