### ISSUE TITLE
Last translation in file is used

### ISSUE THREAD

**Issue by sgrossberndt** [cedricziel/idea-php-typo3-plugin#148]
If a locallang defines multiple languages the shortened label is displayed using the last language in the file, e.g. using this file
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<T3locallang>
	<data type="array">
		<languageKey index="default" type="array">
			<label index="mylabel">English</label>
		</languageKey>
		<languageKey index="de" type="array">
			<label index="mylabel">Deutsch</label>
		</languageKey>
		<languageKey index="fr" type="array">
			<label index="mylabel">Français</label>
		</languageKey>
		<languageKey index="nl" type="array">
			<label index="mylabel">Nederlands</label>
		</languageKey>
		<languageKey index="es" type="array">
			<label index="mylabel">Español</label>
		</languageKey>
	</data>
</T3locallang>
```
`'label' => 'LLL:EXT:xxx/locallang.xml:mylabel',` will be displayed as `'label' => 'Español'`

My spanish is not that fluent I get which field this is so I have to click on it to see at least the label name. Either this should be configurable or the default language should be used.

**Comment by cedricziel** [comment]
That's a great hint - and yes, you're absolutely right. I'm afraid there's a conceptual gap currently, but I'll work it out, somehow.
