### ISSUE TITLE
Question/Feature request: Turn off language file detection?

### ISSUE THREAD

**Issue by rowild** [cedricziel/idea-php-typo3-plugin#156]
I was wondering, if it would be possible to offer a checkbox anywhere, that would allow to turn-off the check for LLL-related issues? Currently that feature is not so useful: as soon as it detects outdated paths (like lang/...), red wavy lines make the developer insecure all the time.

Since there are plugins that intend to support more then just TYPO3 8.*, it cannot be expected, that this behaviour changes too soon. 

Another situation is where an "interim" variable for the LLL path is used (e.g. "news"). There, something like `$ll = EXT:LLL:path/to/lang/files"` is defined to later on be used as `$ll . 'key'`. Here again the plugin causes red wavy lines to appear...

Would be great! Thank you!

**Comment by cedricziel** [comment]
Hi @rowild ,

for string interpolation, you can use a variable that contains the path to the file. As of now it should not end with a colon.

Do you now how language paths are interpolated and where this happens? We could try to infer the origin.

**Comment by rowild** [comment]
Sorry, but I have no idea, what exactly you mean... Where should that variable you talk about be implemented? And as for the second question: ???
I am just a user... sorry... :-(

**Comment by rowild** [comment]
I'd like to pick up this request again, please.
More and more extension developers adapt to the habit of putting the base path of a language file into a variable, e.g.:
```
$langGeneralPath = 'LLL:EXT:lang/locallang_general.xml:';
```

This variable cannot be parsed and therefore shows an error in form of a red wavy line, which is also visible in the tree. This is very, very distracting. 

Is there any way to handle this problem? Would be great!

**Comment by cedricziel** [comment]
With completion available, I really see no point in shortening the translation strings.

Anyways, I pushed a patchset that adresses specifically the ":" case.
