### ISSUE TITLE
"Unresolved translation - this may occur if you defined the translation key only in Typoscript" even if TYPO3 CMS Inspections are disabled

### ISSUE THREAD

**Issue by stat1x** [cedricziel/idea-php-typo3-plugin#203]
Hi,
I get this message "Unresolved translation - this may occur if you defined the translation key only in Typoscript" even if I disable the TYPO3 CMS inspections. Do I miss something?

![image](https://user-images.githubusercontent.com/11523234/43184732-e354c3aa-8fe9-11e8-82e6-ebe719921c4b.png)
![image](https://user-images.githubusercontent.com/11523234/43184763-fd6292ae-8fe9-11e8-956f-33fea9b5a75f.png)

Thanks

**Comment by cedricziel** [comment]
Yes, it's an annotation, not an inspection - I'll see what I can do.
