### ISSUE TITLE
Text selection via keyboard within an LLL: strings slows down the IDE

### ISSUE THREAD

**Issue by monosize** [cedricziel/idea-php-typo3-plugin#209]
To reproduce the behavior:
Place the text cursor in an LLL: string.
Response time for text selection with the keyboard within an LLL: strings is very slow. The entire IDE is then no longer usable. 
The waiting time is a few seconds.
Text selection with the mouse is not affected.

**Comment by cedricziel** [comment]
Should be fixed with #218
