### ISSUE TITLE
Not working in PHPStorm 2018

### ISSUE THREAD

**Issue by daCyberpunk** [cedricziel/idea-php-typo3-plugin#223]
Generally it looks interesting but its not working. I just installed it and expected it to work. Did I miss something?

**Comment by cedricziel** [comment]
What is "not working"?

**Comment by ipf** [comment]
@daCyberpunk Did you restart your IDE after installing the plugin?

**Comment by daCyberpunk** [comment]
Yes I did and I can see some new entries like CE creation and so on. but whatever I try, it just happens nothing. 
As I'm a developer too (I think so) and the Plugins are open source I'm investigating by myself now. :-) If I find something of course I'll report. :-)

**Comment by cedricziel** [comment]
I'd be super glad if you could open individual issues about anything you find.

The plugin does many things that are more or less under the surface so they're not super obvious like providing return types or completion at special places.

Things like file generation are mostly 1st generation features that were added mostly untested and there's a lot of technical debt under the surface.

So in conclusion: I'm super happy about anything you can report, but simply stating 'it doesnt work' is nothing i could really help with :)

Thanks in advance! :)
