### ISSUE TITLE
Update for 2019.2 EAP build 192.4488.6

### ISSUE THREAD

**Issue by liayn** [cedricziel/idea-php-typo3-plugin#286]
Would be great to get a compatible version soonish, so I can upgrade to the EAP release again. Thanks a lot!

**Comment by cedricziel** [comment]
Unfortunately, there's some smaller issues with the current codebase which I am unable to resolve promptly :/

I'll work on it, when I find the time, but here is an artifact so you can at least use the plugin in 2019-2; no guarantee though. You can import it through the plugin manager and it will auto-update once a new release is out :)

Bug reports appreciated!

[TYPO3 CMS Support-192.3.26.ca851f587e-SNAPSHOT.zip](https://github.com/cedricziel/idea-php-typo3-plugin/files/3258975/TYPO3.CMS.Support-192.3.26.ca851f587e-SNAPSHOT.zip)

**Comment by liayn** [comment]
Thanks for your response, Cedric!
I'm not sure though if I understood you correctly.
You said you have some troubles with 2019.2 EAP compatiblity, but on the other hand you provide me a snapshot that should work with 2019.2? What am I missing?

**Comment by cedricziel** [comment]
The plug-in is automatically built and published through Travis - as a safeguard for passing tests. I can, however build the plug-in manually while skipping the tests, which is essentially compiling the code and bringing it in a consumable shape :)

Currently there's a discrepancy with Java 11 (most probably an enhancement to the build matrix) and a failing test for magic finders on extbase repos, but it's perfectly possible that the rest works fine (98 % of tests pass, after all). I hope that answers the question.

**Comment by liayn** [comment]
Thanks. Will give it a shot with the latest EAP and that snapshot tomorrow then.

**Comment by liayn** [comment]
Did you release a new version already? PHP Storm suddenly offered an update, so I didn't even need your snapshot.

**Comment by cedricziel** [comment]
Nope, no update at all, the last update is a little older:

https://plugins.jetbrains.com/plugin/9496-typo3-cms-plugin/versions

**Comment by liayn** [comment]
Strange, because this one is compatible they say... (and that one was not offered on 2019.1)

**Comment by liayn** [comment]
Should I still install your snapshot to help you test it?

**Comment by cedricziel** [comment]
If you can, just use the version offered - i'm not sure why it was offered to you at all.. this is very strange.

Any help is appreciated, but i think i'm covered, thx :)

**Comment by cedricziel** [comment]
FYI, v0.4.0 is tagged and drops support for anything below 192. There's still a lot of stuff to clean up, but at least the functionality is restored :)

Should be available in an update manager near you soon.
