### ISSUE TITLE
AJAX routes are not identified

### ISSUE THREAD

**Issue by liayn** [cedricziel/idea-php-typo3-plugin#288]
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Classes/Page/PageRenderer.php#L1436

`$requireJsConfig['typo3BaseUrl'] = (string)$uriBuilder->buildUriFromRoute('ajax_core_requirejs');`

`ajax_core_requirejs` is not found, which must be searched as `core_requirejs`.

Related: #50

**Comment by liayn** [comment]
Version 0.2.4

**Comment by cedricziel** [comment]
Version 0.2.4 is an old fallback version one gets when there is no version for the current IDE version. I added a test for ajax routes specifically though.

**Comment by liayn** [comment]
Thanks. The issue was very old indeed.
