### ISSUE TITLE
Magic Methods not proper supported

### ISSUE THREAD

**Issue by antonfries** [cedricziel/idea-php-typo3-plugin#289]
Hey Cedric, im using The TYPO3 CMS Plugin now in my company and i found an problem with the resolving of magic methods:
If i use $this->productRepository->findOneByArticleNumber($controlUnit);
Its marking me yellow because the required arguments for the __call function is not given
But the call itself is proper, im giving the information "ArticleNumber" in the function name and the arguments in the brackets ( )
![magicMethod](https://user-images.githubusercontent.com/49792220/59921272-72aeac80-942d-11e9-870e-f6b02fbe3a1e.jpg)

**Comment by antonfries** [comment]
Are there any updates on this?

**Comment by cedricziel** [comment]
Unfortunately not. I evaluated different methods of doing this better, but to no avail. Will keep you posted once something changes

**Comment by cedricziel** [comment]
@antonfries we are suppressing the inspection for undefined methods beginning with 0.5.2. Also the custom reference to the `__call` method was removed.

It should be much less disturbing now.
