### ISSUE TITLE
Controller action methods are marked as non used

### ISSUE THREAD

**Issue by antonfries** [cedricziel/idea-php-typo3-plugin#291]
![unusedActionsInControllers](https://user-images.githubusercontent.com/49792220/62368885-3727f780-b52e-11e9-8cf7-3a45dc142925.jpg)

**Comment by kamilmaliszewski** [comment]
+1

**Comment by cedricziel** [comment]
Hint to my future-self: this could potentially be solved by a InspectionSuppressor on the method when the parent class ends in `Controller`.
