### ISSUE TITLE
PhpStorm show incompatibility with 2019.2

### ISSUE THREAD

**Issue by mediaessenz** [cedricziel/idea-php-typo3-plugin#292]
Version v0.2.48 is shown as incompatible with PhpStorm 2019.2

**Comment by cedricziel** [comment]
Please visit your PhpStorm Extension Update Section. There should be an update available. https://plugins.jetbrains.com/plugin/9496-typo3-cms-plugin/update/65426

**Comment by mediaessenz** [comment]
After reinstall (uninstall + restart ide + install) the plugin works fine (again) :-)
