### ISSUE TITLE
All classes are undefined

### ISSUE THREAD

**Issue by Smove** [cedricziel/idea-php-typo3-plugin#298]
After updating the cms plugin to 0.4.1(193.4.1) all classes are marked as undefined.

**Comment by tkieslich** [comment]
I can confirm this.

**Comment by ipf** [comment]
Happens on IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 27, 2019

**Comment by cedricziel** [comment]
Okay, acknowledged. Thanks for the report. Will look into it ASAP.

**Comment by cedricziel** [comment]
Fixed. Will be released as 0.4.2

A new version can be downloaded from the GitHub releases page once Travis has built the  tag.

https://github.com/cedricziel/idea-php-typo3-plugin/releases/tag/v0.4.2
