### ISSUE TITLE
Add type helpers for TSFE, BE_USER globals

### ISSUE THREAD

**Issue by NamelessCoder** [cedricziel/idea-php-typo3-plugin#30]
These often-used globals, although we follow best practice and use getter methods to return instances and then annotate these getters, would be nice to gain introspection into - not least when you open one of those very old legacy projects that access these globals willy-nilly.

**Comment by cedricziel** [comment]
Thx - I'll split that up in multiple tickets - are there any other places you can imagine, where the IDE will tell the return value is `mixed`, `object` or unknown that come to mind?

**Comment by cedricziel** [comment]
That was an easy pick - thanks for your suggestions!

**Comment by NamelessCoder** [comment]
Nice! No - I have no other suggestions off the top of my head (which aren't already recorded as issues).
