### ISSUE TITLE
Type inference for objectManager::get does not work

### ISSUE THREAD

**Issue by liayn** [cedricziel/idea-php-typo3-plugin#305]
PhpStorm 2020.1 Build #PS-201.6668.153, built on April 13, 2020
Plugin version: 201.5.0

Demo code in an extbase repository:
```
$dataMapper = $this->objectManager->get(\TYPO3\CMS\Extbase\Persistence\Generic\Mapper\DataMapper::class);
```

`$dataMapper` is of type `object`.

**Comment by cedricziel** [comment]
Is the objectmanager inferred as being of type ObjectManagerInterface/ObjectManager?

**Comment by liayn** [comment]
It shows `ObjectManagerInterface`

**Comment by cedricziel** [comment]
Checked with 9d84e9b9f198a506e8d1b45214f32382f4319bd2, but I cant seem to reproduce the behaviour.. is the plugin activated?

**Comment by liayn** [comment]
Double-checked the settings, yes it is activated

**Comment by liayn** [comment]
Updated to 201.5.1 today, still the same problem.

**Comment by liayn** [comment]
I think I finally found the main reason: The problem occurs if the Core is only added via Include Path (External Libraries). If the Core is present in the current project directly everything works.

What does not work:
Open extension as project and set core as Include Path.

What seems to work:
Open a whole website project where the Core source is part of the project.

**Comment by nitori** [comment]
I have the same issue, but I can't get it to work even if I include the typo3 source directly in the project.

**Comment by liayn** [comment]
Thanks for the update.

I updated to PhpStorm 2020.1.1 (Build #PS-201.7223.96, built on April 30, 2020) and the plugin (201.5.4) and I can confirm that #306 is indeed resolved.

Unfortunately not this one here.

Using `$uriBuilder = $this->objectManager->get(UriBuilder::class);` inside an Extbase controller within a project with TYPO3 v8 core source present only yields `object` as type for `$uriBuilder`.

**Comment by cedricziel** [comment]
Hmm. Neverending issue... re-opening for further tracking :)

**Comment by cedricziel** [comment]
I am absolutely out of luck:

```
PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
Licensed to TYPO3 CMS Plugins for IntelliJ IDEA / PhpStorm / Cedric Ziel
Subscription is active until November 19, 2020
For non-commercial open source development only.
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: run.processes.with.pty=TRUE
Non-Bundled Plugins: PsiViewer, com.cedricziel.idea.typo3
```

<img width="1066" alt="Bildschirmfoto 2020-05-02 um 10 25 57" src="https://user-images.githubusercontent.com/418970/80859258-7a4efc80-8c5f-11ea-8135-c491fda5f4e7.png">

**Comment by cedricziel** [comment]
Any other non-bundled plugins that might break it?

**Comment by liayn** [comment]
```
PhpStorm 2020.1.1
Build #PS-201.7223.96, built on April 30, 2020
....
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 3891M
Cores: 12
Registry: run.processes.with.pty=TRUE, ide.tooltip.initialDelay=720
Non-Bundled Plugins: com.urswolfer.intellij.plugin.gerrit, YAML/Ansible support, com.intellij.ideolog, ru.adelf.idea.dotenv, com.cedricziel.idea.typo3, de.espend.idea.php.annotation, de.sgalinski.fluid.plugin.id, de.sgalinski.typoscript.enterprise.plugin.id
```

**Comment by liayn** [comment]
![grafik](https://user-images.githubusercontent.com/222377/80891057-d5b1d680-8cc1-11ea-80bf-cb56be4b47bd.png)

**Comment by liayn** [comment]
I disabled all non-builtin plugins and invalidated caches and restarted... still no change :-(

**Comment by froemken** [comment]
Interesting: I have just deactivated the `PHP Inspections (EA Extended)` Plugin, restarted PhpStorm, and wow, I was asked if I want to use auto-settings of your TYPO3-Plugin suddenly. After activating them (again), auto-completion works correctly.

**Comment by liayn** [comment]
I don't know what happened, but suddenly it's working again. Closing this again.

**Comment by rlvk-tc** [comment]
This is still an issue. We are multiple people experiencing it still.
We have the core code mapped in external libraries, which is basically the only way we can work. It once worked, but it's been a while since it worked correctly. 

It would be great to open this issue again 😄
