### ISSUE TITLE
Inspection suggests potentially invalid code, which is wrong

### ISSUE THREAD

**Issue by liayn** [cedricziel/idea-php-typo3-plugin#306]
```
$log = GeneralUtility::makeInstance(LogManager::class)->getLogger(__CLASS__);
```

`getLogger` is marked by an inspection with the text:

> Potentially polymorphic call. The code may be inoperable depending on the actual class instance passed as the argument.

This inspection is wrong, as the return value of makeInstance is clear.

**Comment by cedricziel** [comment]
I am unable to reproduce this. Which version of the PHP plugin are you using?

The return value is correctly inferred as far as I can see, the polymorphic part is about an invocation of a method where polymorphism causes existence in one implementation, but not in others.

There are 90ish occurrences of the polymorphic inspection triggering in TYPO3 10, but not the above snippet.

Happy to re-open on more information. Thanks for reporting! <3

**Comment by liayn** [comment]
PhpStorm 2020.1 Build #PS-201.6668.153, built on April 13, 2020
Plugin version: 201.5.0

I restructured the code to:
```
$logm = GeneralUtility::makeInstance(LogManager::class);
$log = $logm->getLogger(__CLASS__);
```
now `$logm` has type `object|TYPO3\CMS\Core\SingletonInterface`
and therefore the polymorphic inspection triggeres for `getLogger` as this method is of course not defined on every object.

The polymorphic things is just a consequence of the wrong type of `$logm`.

What more information can I provide so that you are able to reproduce?

**Comment by liayn** [comment]
@cedricziel  Updated to 201.5.1 today, still the same problem

**Comment by liayn** [comment]
Updated to 201.5.2, still the same, but I noticed something:

I'm using Core v8 as reference. If I switch to v9 the type infers to:
`object|Psr\Log\LoggerAwareInterface|TYPO3\CMS\Core\SingletonInterface`

This obviously has something to do with the core version!

**Comment by cedricziel** [comment]
That's some very useful information. Thanks, i'll double check it.

**Comment by liayn** [comment]
I think this can be handled with #305 for the time being.
