### ISSUE TITLE
PhpStorm indexing loop

### ISSUE THREAD

**Issue by echavaillaz** [cedricziel/idea-php-typo3-plugin#310]
Hi,

With PhpStorm 2020.1, the indexing is broken (infinite loop) with the TYPO3 plugin installed.

Thanks

**Comment by cedricziel** [comment]
Please clear the index and restart the IDE and check if the problem arises again. Thanks

**Comment by echavaillaz** [comment]
Yes I try but always the same, a loop...

**Comment by cedricziel** [comment]
I cannot reproduce it. Please clear the index manually.

Did you check if other plugins might be involved?

**Comment by echavaillaz** [comment]
I will try, how can I clear the index manually?

**Comment by n3amil** [comment]
can confirm this issue, if i disable the plugin the index works fine and if enabled the index wont finish. Just happend with the latest plugin update.

**Comment by cedricziel** [comment]
For clearing the caches, there's a knowledge base entry at JetBrains: https://www.jetbrains.com/help/phpstorm/cleaning-system-cache.html

A hard solution would be to delete the relevant folders from the filesystem and have it reindex all the stuff.

**Comment by echavaillaz** [comment]
Strange now it works (and I don't try to clear the system cache).

Thanks
