### ISSUE TITLE
Plugin incomptibel to latest IntellJ IDEA version (needs IDE buidl 213.* or earlier"

### ISSUE THREAD

**Issue by fgerards** [cedricziel/idea-php-typo3-plugin#384]
**Describe the bug**
PLugin incomptibel to latest IntellJ IDEA version (needs IDE buidl 213.* or earlier"

**To Reproduce**
* Install plugin
* see error

**Expected behavior**
Plugin should be compatible with current IDE version

**Versions**
latest plugin version, IDE v2022.1.2

**Comment by PfefferT** [comment]
Unfortunately, this incompatibility message comes more and more often. In the previous versions, the support was felt to be faster here.

**Comment by saschaende** [comment]
Everything around TYPO3 is slowly lacking support, that's why I have now completely reprogrammed my website with Laravel and since then everything is so much faster and easier ....

**Comment by fgerards** [comment]
lol, you cant compare Laravel framework with an enterprise CMS system as TYPO3 with tons of out-of-the-box features - try to do www.dallmayr.de or www.motel-one.com etc. with laravel only - you will end up in a mess and an unmaintainable system and have 5 times the cost for initial implementation.

**Comment by saschaende** [comment]
Yes i can.

And all companies i know are switching off from TYPO3 - most of them to wordpress. For example Lindt also switched from TYPO3 to another solution. https://www.lindt.de/

If you have a look at the current cms usage statistics, TYPO3 lost MANY customers - over 40% in the last 7 years - so it is a global phenomenon.

Remember my words: TYPO3 will die within the next 10 years because of a lack of programmers (that want to deal with this crappy cms) and customers.

**Comment by saschaende** [comment]
--> http://www.dallmayr.de/

They even are not able to manage a redirect to the SSL version - Chrome shows "insecure website". Thats unprofessional and not good for SEO.

--> http://www.motel-one.com/

I saw many websites with Wordpress like that. Probably the only difference is, that with TYPO3 this just costs 1000% more time and money.

Sorry...

**Comment by fgerards** [comment]
I see you mix up things and have no clue, what you are talking about. Motel-one.com or other sites with multidomain/multilinguale with fallbacks and workspaces are manageable onlywith an enterprise grade CMS. WordPress is a Blog system, which pretends to be CMS.  If you don’t know how to separate concerns and call things crappy, which you don’t fully understand, so be it

**Comment by TheNaderio** [comment]
You all know that this is a third party plugin?
And… oh - that’s on GitHub, try to contribute code and bugfixes. Or fork it and make your own plugin. 
Don't blame TYPO3 here, one doesn't have much to do with the other

**Comment by cedricziel** [comment]
Sorry for the initial reporter, but I think it's better to lock this issue.

This project is welcoming bugfixes and enhancements. It is just that I don't have any touchpoints in my professional setting with TYPO3 anymore.

**Comment by cedricziel** [comment]
Resolved. Released versions for both 222 and 223
