### ISSUE TITLE
Inspection bug, UriBuilder + routes

### ISSUE THREAD

**Issue by NamelessCoder** [cedricziel/idea-php-typo3-plugin#50]
I have a tiny issue to report - possibly only with the single method shown in this screenshot:

![screen shot 2017-04-30 at 07 32 46](https://cloud.githubusercontent.com/assets/2228052/25561933/913f0c90-2d77-11e7-93dc-65a286600c40.png)

The first parameter is recognised as a route, so that's fine (the light bulb only contains the normal string conversion choices). The second parameter however is supposed to be an array of arbitrary URL parameters - but the keys in the array are both reported as "unresolved route" (the red underline, has `Unresolved route` as tooltip on mouse over).

The result is that the file is marked as containing errors although it doesn't.

**Comment by cedricziel** [comment]
Alright - thx for reporting - that's no expected behaviour :)

**Comment by cedricziel** [comment]
Fixed in v0.2.3, already updated in the repository - might take a day, but probably 2 to propagate :)

**Comment by cedricziel** [comment]
I introduced a new bug that results in the same issue. Fix upcoming.
