### ISSUE TITLE
Table name completion in strings?

### ISSUE THREAD

**Issue by NamelessCoder** [cedricziel/idea-php-typo3-plugin#57]
I don't even know if this is possible, but I came up with this idea while working on a TCA-heavy project:

> Would it be possible to auto-complete table names that are added to TCA, when writing strings?

This could be really helpful, even if it is for example limited to only happen in certain files, e.g. TCA files.

It could also make sense to target any argument named `$table` or `$tableName` and/or simply targeting the table-specific arguments on Doctrine QueryBuilder, e.g. all the select(), getConnectionForTable(), getQueryBuilderForTable(), and any alias-argument for field selection methods.

This could perhaps also be combined with inspections to report bad values in known table arguments in functions such as the `ExtensionManagementUtility::addTCAcolumns` function.

Something universal which triggers on argument name could be opt-in, but for people who write consistent variable names it would be very useful.

**Comment by cedricziel** [comment]
Thx for your suggestion!

I don't think matching the argument-name is a good idea, but I'll think about it (I don't like the magic and I'm pretty sure we wouldnt match all of those arguments :) ). Could you help compiling a list of methods where we need completion for starters?
