### ISSUE TITLE
Add Path Referencing for 'EXT:foo/...' resource paths

### ISSUE THREAD

**Issue by cedricziel** [cedricziel/idea-php-typo3-plugin#66]
* [x] A GotoDeclarationHandler for StringLiterals that matches the `EXT:foo` syntax [ #74  ]

**Comment by cedricziel** [comment]
Fixed with #74

**Comment by RauchF** [comment]
Hi, would it be possible to make the extension root path configurable? The current version marks every `EXT:` resource path as invalid, because the project structure has the extensions reside in a sub directory.

**Comment by cedricziel** [comment]
@RauchF exactly that has been proposed in #87 , mind if we discuss it further over there?

**Comment by RauchF** [comment]
@cedricziel sorry, didn't see that one. I'll head over there :)
