### ISSUE TITLE
GeneralUtility::getFileAbsFileName has issues with trailing slashes

### ISSUE THREAD

**Issue by nitori** [cedricziel/idea-php-typo3-plugin#89]
Hi,

I noticed that `GeneralUtility::getFileAbsFileName` has a few issues, if you want to specify a path to a directory that has a trailing slash at the end.

In the screenshot below the following example was used:

```
GeneralUtility::getFileAbsFileName("EXT:consumption_calculator/" . $relFilePath);
```

![IDE Screenshot](http://img.xrmb2.net/images/469230.png)

which results in red marking under the string. It does work correctly if I remove the trailing slash. The behaviour is the same with or without the concatenated variable (trailing slash: error; no trailing slash: good).

Secondly, I think, even if it does try to resolve and doesn't find the resource, I do not think it should be marked with the heavy red, that's visible (and annoying) throughout the directory tree on the left side (see screenshot).

And lastly, to my opinion it does not make much sense to try to resolve the path when variables/dynamic content is involved, right?

Greetings
Nitori

**Comment by cedricziel** [comment]
I have created a patch for the trailing slashes in #90 , could you check the included build artifact?

I need to think about your last two points.

Thx for reporting the issue!
